spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6nx321q9ee103aw.mysql.rds.aliyuncs.com:3306/total_ssm_stg?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&functionsNeverReturnBlobs=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: total_stg_user
    password: total8uhb(IJN
  redis:
    database: 15
    host: 111.161.18.27
    port: 16381
    password: 3edasX22
    jedis:
      pool:
        max-active: 16
        max-wait: -1
        max-idle: 16
        min-idle: 0
    timeout: 10000
wjj:
  worker:
    easyfood:
      notifyUrl: https://api.day.app/ZLRvSrSCfwiy2AyuHKX8yG/{title}/{value}
      addressKeyWord: 后
      userId: 6243a423ce996400016ed7ee
      userToken: 751d086e3c30f8ae07ce466f4463c58c

